/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface XTable {
    }
    interface XTableCell {
        "getMarkup": () => Promise<HTMLTableCellElement>;
    }
    interface XTableRow {
        "getMarkup": () => Promise<HTMLTableRowElement>;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLXTableElement extends Components.XTable, HTMLStencilElement {
    }
    var HTMLXTableElement: {
        prototype: HTMLXTableElement;
        new (): HTMLXTableElement;
    };
    interface HTMLXTableCellElement extends Components.XTableCell, HTMLStencilElement {
    }
    var HTMLXTableCellElement: {
        prototype: HTMLXTableCellElement;
        new (): HTMLXTableCellElement;
    };
    interface HTMLXTableRowElement extends Components.XTableRow, HTMLStencilElement {
    }
    var HTMLXTableRowElement: {
        prototype: HTMLXTableRowElement;
        new (): HTMLXTableRowElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "x-table": HTMLXTableElement;
        "x-table-cell": HTMLXTableCellElement;
        "x-table-row": HTMLXTableRowElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface XTable {
    }
    interface XTableCell {
    }
    interface XTableRow {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "x-table": XTable;
        "x-table-cell": XTableCell;
        "x-table-row": XTableRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "x-table": LocalJSX.XTable & JSXBase.HTMLAttributes<HTMLXTableElement>;
            "x-table-cell": LocalJSX.XTableCell & JSXBase.HTMLAttributes<HTMLXTableCellElement>;
            "x-table-row": LocalJSX.XTableRow & JSXBase.HTMLAttributes<HTMLXTableRowElement>;
        }
    }
}
